agent_name: {{ cookiecutter.agent_name }}
task_server_name: {{ cookiecutter.task_server_name }}
checkpoint_db_name: {{ cookiecutter.checkpoint_db_name }}
replicas: {{ cookiecutter.replicas }}
iam_role_arn: {{ cookiecutter.iam_role_arn }}